Protocol: test
Address: test
FixedPublicAddress: tet
HostNetwork:
  MinTimeout: 22
  MaxTimeout: 3
  TimeoutMult: 4
  SignMessages: true
  HandshakeSessionTTL: 23
Clients:
  first:
    ID: 123
    Address: test-123
  second:
    ID: 456
    Address: test-456